import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/navigation/sidebar";
import RightSidebar from "@/components/navigation/right-sidebar";

const interFont = Inter({
  weight: "400",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Oak Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interFont.className} antialiased`}>
        <div className="flex min-h-screen bg-gradient-to-br from-[#393e41] to-[#5c5e5f] text-white">
          <Sidebar />
          {/* main content  */}
          <div className="flex mb-12 sm:ml-16 sm:mr-64 flex-col">
            <main className="flex-grow p-4 md:p-8   w-full  md:max-w-[calc(100vw-20rem)]">
              {children}
            </main>
          </div>
          {/* right side bar  */}
          <RightSidebar />
        </div>
      </body>
    </html>
  );
}